class AppStrings {
  static String email = 'email';
  static String password = 'password';
  static String userName = 'UserName';
  static String rememberme = 'Rememberme';
  static String login = 'login';
  static String yes = 'yes';
  static String cancel = 'cancel';
  static String signup = 'signUp';
  static String chooseLocation = 'Choose Location';
  static String or = 'OR';
  static String change = 'Change';
  static String send = 'Send';
  static String useMyCrrunetLocation = 'Use My Crrunet Location';
  static String checkemailtext = 'Enter Your E-mail and we will send you code';
  static String skip = 'Skip';
  static String code = 'Code';
  static String newpasswordtext = 'Enter New Password';
  static String forgetPassword = 'Forget password';
  static String myorder = "My order";
  static String mylocation = 'My Location';
  static String setting = 'Setting';
  static String profile = 'Profile';
  static String pleasechooseyourlanguage = 'pleasechooseyourlanguage';
  static String donthaveaccount = "donthaveanaccount";
  static String alreadyhaveaccount = "Alreadyhaveanaccount";
  static String create = 'create';
  static const String creataccount = 'Create Account';
  static const String creataccounttitle = 'Fill your information below';
  static String valiemail = 'pleasenteryourvalidemail';
  static String valiepassword = 'PleaseEnteryourPassword';
  static String join = 'Join';
  static String logoutsure = 'Are you sure you want to logOut';
  static String failed = 'Failed';
  static String loginSucessfully = "loginSucessfully";
  static String creatSucessfully = "CreatProjectSucessfully";
  static String sigupSucessfully = "SignupSucessfully";
  static String loginFailed = "LoginFailed";
  static String signupFailed = "Signupfailed";
  static String readmoretext = 'readmoretext';
  static String changelan = 'Changelanguage';
  static String language = 'language';
  static String enterprojectsID = 'Enterproject’sID';
  static String confirm = 'confirm';

  static String logout = 'logout';
  static String logoutSuccess = 'LogOut Successfully';
  static String delete = 'Delete';
  static String edit = 'Edit';

  static const String on1title =
      'Welcome to the World of Handcrafted Creativity!';
  static const String on1subtitle =
      'Explore our smart, stylish, and trend setting collection that will elevate your look.';
  static const String on2title = 'Shop Now and Discover Unique Handicrafts';
  static const String on2subtitle =
      'Uncover an array of the finest fashion trends tailored just for you.';
  static const String on3title = 'Featured Products for You';
  static const String on3subtitle =
      'Experience the convenience of fast and reliable delivery services to your doorstep.';
  static const String productDetails = 'Product Details :';
  static const String price = 'Price';
  static const String season = 'Season';
  static const String nameErrorMsg = 'Please enter your Name';
  static const String gender = 'Gender';
  static const String description = 'Description';
  static const String size = 'Size';
  static const String cost = 'Cost';
  static const String comment = 'Comment';
  static const String search = 'Search';
  static const String home = 'Home';
  static const String order = 'Order';
  static const String category = 'Category';
  static const String logintitle = "Hi! Welcome back, you've been missed";
  static const String passwordisnotidentical = 'password is not identical';
  static const String passwordupper =
      'Password must contain at least one uppercase letter';
  static const String passwordlenght =
      'Password must be at least 5 characters long';
  static const String passwordchar =
      'Password must contain at least one special character';
  static const String confirmpassword = 'Confirm Password';
  static const String phone = 'Phone number';
  static const String pleasechooseimage = "Please choose image";
  static const String fromcamera = 'From Camera';
  static const String fromGallery = 'From Gallery';
  static const String deleteimage = 'delete image';
  static const String instructionsForTakePhoto = 'instructionsForTakePhoto';
  static const String pleaseForImage =
      'For a great and useful experience, please follow these instructions.';
  static String discount = 'discount';
  static String bazaar = 'bazaar';
  static String addtocart = 'add to cart';
  static String tryagain = 'try again';
  static String totalPrice = 'Total Price';
  static String confirmOrder = 'Confirm Order';
  static String dateOfOrder = 'Date of order';
  static String isdeliverd = 'Is deliverd';
  static String addrating = 'Add Rating';
  static String addratingtext = 'Rate this product';
  static String checkYouremail = 'Check Your Email';
  static String auction = 'Bazaar';
  static String addcomment = 'Add Comment';
  static String notexthere = 'No text here';
  static String update = 'Update';
  static String deleted = 'Deleted';
  static String updated = 'Updated';
  static String somethingwentwrong = 'something went wrong';
  static String nocomment = 'No Comments Yet';
  static String productinauction = 'Products available in this bazaar';
  static String LocationConfirm = 'Location Confirm';
  static String LocationDetails = 'Location Details';
  static String theArea = 'The Area';
  static String theStreet = 'The Street';
  static String myAddresses = 'My Addressess';
  static String makerauction = 'The Artisans participating in this bazzar';
  static String example = 'Example';
  static String addNewAddress = 'Add new address';
  static String noaddressesfound = 'No addresses found';
  static String cart = 'Cart';
  static String noProductfoundInCart = 'No Product Found In Cart';
  static String pleaseEnterthelocation = 'Please Enter The Location';
  static String fullOrderPrice = 'Full Order Price';
  static String outOfStock = 'Out Of Stock';
  static String theFinalOrder = 'The final order';
  static String availableQuantity = 'Available Quantity';
  static String enterTheVaildNumber = 'Please enter a valid number';
  static String theOrderGetSuccessfully = 'The order get successfully';
}
